# Dockerfile

# 1. ESCOLHA A IMAGEM BASE
# Retornamos para a slim (mais leve) para que possamos controlar as ferramentas.
FROM python:3.9-slim 

# 2. DEFINE O DIRETÓRIO DE TRABALHO
WORKDIR /app

# 3. INSTALA FERRAMENTAS DO SISTEMA (A SOLUÇÃO)
# O Prophet precisa dessas ferramentas para ser compilado com sucesso.
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gfortran \
    # Limpa o cache para reduzir o tamanho da imagem
    && rm -rf /var/lib/apt/lists/*

# 4. COPIA E INSTALA DEPENDÊNCIAS PYTHON
COPY requirements.txt .

# Instala as bibliotecas. Agora, as ferramentas necessárias estão instaladas.
RUN pip install --no-cache-dir -r requirements.txt

# 5. COPIA O CÓDIGO-FONTE
COPY src/ .

# 6. DEFINE O PONTO DE ENTRADA
ENTRYPOINT ["python", "main.py"]
